[package]
name = "rust_aoc"
version = "0.1.0"
authors = ["Sergey Ivanov <sergey.ivanov@mail.ru>"]
edition = "2018"

[dependencies]
nom = "6"
matches = "0.1"
itertools = "0.10"
md-5 = "0.9.1"
serde_json = "1.0.61"